#!/bin/bash

BACKGROUND='#161616'
FOREGROUND='#CACACA'
YELLOW='#FF8000'

while [ "$select" != "NO" -a "$select" != "YES" ]; do
    select=$(echo -e 'NO\nYES' | dmenu -i \
        -nb $BACKGROUND -nf $FOREGROUND -sb $YELLOW -sf $BACKGROUND \
        -fn 'Fira Mono:bold:pixelsize=18' \
        -p "Do you really want to exit $1, thus ending the session?")
    [ -z "$select" ] && exit 0
done

if [ "$select" = "NO" ]; then
    exit 0
else
    if [ $1 == "i3" ]; then
        i3-msg exit
    else
        swaymsg exit
    fi
fi
