#!/bin/bash

rofi \
    -show drun \
    -location 1 -width 100 \
    -lines 5 -columns 5 \
    -hide-scrollbar \
    -matching fuzzy \
    -display-drun "Launch: " \
    -font "Fira Mono 13" \
    -theme $HOME/.config/rofi/nixpulvis.rasi \
    -show-icons
