#!/bin/bash

i3lock \
    --radius=150 \
    --clock --time-font='Fira Mono' --timesize=30 --timecolor=cacacaff --timestr='%T %Z' \
    --date-font='Fira Mono' --datesize=20 --datecolor=cacacaff --datestr='%a %F' \
    --color=161616 \
    --insidecolor=282c34ff --ringcolor=cacacaff \
    --insidevercolor=00A3FEff --ringvercolor=00A3FEff \
    --insidewrongcolor=FE340Aff --ringwrongcolor=FE340Aff \
    --linecolor=161616ff --keyhlcolor=CACACAff --bshlcolor=FF8000ff \
    --separatorcolor=cacacaff
