#!/bin/bash

i3lock \
    --radius=150 \
    --clock --time-font='Fira Mono' --time-size=30 --time-color=cacacaff --time-str='%T %Z' \
    --date-font='Fira Mono' --date-size=20 --date-color=cacacaff --date-str='%a %F' \
    --color=161616 \
    --inside-color=282c34ff --ring-color=cacacaff \
    --insidever-color=00a3feff --ringver-color=00a3feff \
    --insidewrong-color=fe340aff --ringwrong-color=fe340aff \
    --line-color=161616ff --keyhl-color=ff8000ff --bshl-color=ff8000ff \
    --separator-color=cacacaff \
    --wrong-text="incorrect" --noinput-text="clear"
