#!/bin/bash
set -e

# Install hub the GitHub wrapper.
sudo pacman -S --needed --noconfirm hub

# Install our fun quote generator.
sudo pacman -S --needed --noconfirm fortune-mod

# Jump into fish.
ln -frs bashrc $HOME/.bashrc

# Install the fish config, and my custom binaries.
mkdir -p $HOME/.config/fish
ln -frs config.fish $HOME/.config/fish/config.fish
mkdir -p $HOME/.bin
ln -frs share-network $HOME/.bin/share-network

