#!/bin/bash
set -e

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

USER=$1

# Ensure this script is called by the root user.
if [[ "`whoami`" != "root" ]]; then
    echo "You must run this script as root."
    exit 1
fi

# Ensure root dotfiles have been installed before any other users.
if [[ ! -f /root/.dotfiles ]] && [[ "$USER" != "root" ]]; then
    echo "You must first run \`./install root\`."
    exit 1
fi

# Create the user (if needed).
if ! id -u $USER &> /dev/null; then
    # TODO: flag for sudo group.
    useradd -m -G wheel -s /usr/bin/fish $USER
fi

# Install each of the user's modules.
if [[ -d $USER ]]; then
    for module in $(ls $USER); do
        cd $USER/$module
        pretty_module=`echo $module | cut -d '_' -f2`
        echo "${green}Installing $USER $pretty_module...${reset} "
        if [[ "$USER" == "root" ]]; then
            cmd="./install"
        else
            cmd="sudo -u $USER ./install"
        fi
        if ! $cmd &> /dev/null; then
            echo "${red}failed${reset}."
            exit 1
        fi
        cd ../..
    done
fi

# Indicate we've install the dotfiles for $USER.
if [[ "$USER" == "root" ]]; then
    touch /root/.dotfiles
else
    touch /home/$USER/.dotfiles
fi

