#!/bin/bash
set -e

# Install the Xorg server.
sudo pacman -S --needed --noconfirm xorg xorg-xinit

# Install i3 WM, and supporting tools.
# TODO: We might need to fork this to fix a border issue.
sudo pacman -S --needed --noconfirm i3-wm i3blocks dmenu rofi feh
yaourt -S --needed --noconfirm i3lock-color
yaourt -S --needed --noconfirm light

# Install font-awesome for icons.
sudo pacman -S --noconfirm ttf-font-awesome

ln -frs bash_profile $HOME/.bash_profile
ln -frs xinitrc $HOME/.xinitrc
mkdir -p $HOME/.X
ln -frs backdrop* $HOME/.X
mkdir -p $HOME/.config/i3
ln -frs config launch terminal exit lock $HOME/.config/i3/
mkdir -p $HOME/.config/i3blocks
ln -frs blocks_config $HOME/.config/i3blocks/config
ln -frs brightness $HOME/.config/i3blocks/
mkdir -p $HOME/.config/rofi
ln -frs onedark.rasi $HOME/.config/rofi/

# Set default desktop wallpaper randomly.
choice=`shuf -i 1-3 -n 1`
ln -frs $HOME/.X/backdrop${choice}.png $HOME/.X/backdrop.png

