#!/bin/bash
set -e

# Don't reinstall.
if [ -x "$(command -v ruby)" ]; then
    exit 0
fi

# Install Ruby, and our ruby environment.
# TODO: Install Rails.
if [[ ! -d $HOME/.rbenv ]]; then
    git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
    mkdir $HOME/.rbenv/plugins
    git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build
fi

$HOME/.rbenv/bin/rbenv install --skip-existing 2.5.0
$HOME/.rbenv/bin/rbenv rehash

