#!/bin/bash
set -e

# Don't reinstall.
if [ -x "$(command -v yaourt)" ]; then
    exit 0
fi

# Install Yaourt for AUR package installation.
git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si --noconfirm
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si --noconfirm
cd ..
rm -rf package-query yaourt

