#!/bin/bash
set -e

# Don't reinstall.
if [ -x "$(command -v rustc)" ]; then
    exit 0
fi

# Install rustup and stable rust.
sudo pacman -S --noconfirm rustup
rustup toolchain install stable
rustup default stable

# Allows running rust files as scripts.
cargo install cargo-script

