#!/bin/bash
# Copyright (C) 2015 Martín Cigorraga <archlinux.us: msx>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Check mouse event
case $BLOCK_BUTTON in
    3)
    amixer set Capture toggle 2>&1 > /dev/null
esac

# Determine mic's state
channels=$(amixer get Capture | sed -nE "s/Capture channels: (.*)/\1/p")
mic_active=0
IFS='-'
for channel in $channels; do
    channel=$(echo $channel | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    if [[ -n $(amixer get Capture | grep "$channel:.*\[on\]") ]]; then
        mic_active=1
    fi
done

# Toggle mic's state
case $mic_active in
    0)
    echo "  mute";
    exit 0;
    ;;
    1)
    echo "  open ";
    exit 33;
    ;;
    *)
    echo "no mic";
    exit 0;
    ;;
esac

exit 0;
