#!/bin/bash
set -e

install_yaourt() {
    # Install an AUR helper command.
    # TODO: Detect and/or flag for reinstall.
    if [ ! -x "$(command -v yaourt)" ]; then
        # Install Yaourt for AUR package installation.
        git clone https://aur.archlinux.org/package-query.git
        cd package-query
        makepkg -si --noconfirm
        cd ..
        git clone https://aur.archlinux.org/yaourt.git
        cd yaourt
        makepkg -si --noconfirm
        cd ..
        rm -rf package-query yaourt
    else
        echo "skipping yaourt install"
    fi
}

install_fonts() {
    # Mozilla's great fonts.
    sudo pacman -S --needed --noconfirm ttf-fira-mono ttf-fira-sans
}

install_terminal() {
    # Install our terminal, Alacritty.
    yaourt -S --needed --noconfirm alacritty
    mkdir -p $HOME/.config/alacritty
    ln -frs .config/alacritty/{alacritty,colors,bindings}.toml $HOME/.config/alacritty/

    # Fallback terminal(s)
    sudo pacman -S --needed --noconfirm xterm rxvt-unicode
}

install_shell() {
    # Install our fun quote generator.
    sudo pacman -S --needed --noconfirm fortune-mod

    # Install the fish shell, to be used by all.
    sudo pacman -S --needed --noconfirm fish
    mkdir -p $HOME/.config/fish
    ln -frs .config/fish/config.fish $HOME/.config/fish/config.fish

    # Jump into fish.
    # TODO: oursh without bash at all.
    ln -frs .bash_profile $HOME/.bash_profile
    ln -frs .bashrc $HOME/.bashrc
}

install_bin() {
    mkdir -p $HOME/.bin
    ln -fs /dotfiles/bin/* $HOME/.bin

    sudo pacman -S --needed --noconfirm pass pass-otp borg python-packaging python-llfuse
}

install_editor() {
    sudo pacman -S --needed --noconfirm ripgrep

    ln -frs .vimrc $HOME/.vimrc
    mkdir -p $HOME/.vim/after/syntax/
    ln -frs .vim/after/syntax/{rust,syncolor}.vim $HOME/.vim/after/syntax/
    mkdir -p $HOME/.vim/autoload/lightline/colorscheme/
    ln -frs .vim/autoload/lightline/colorscheme/nixpulvis.vim /home/nixpulvis/.vim/autoload/lightline/colorscheme/
    mkdir -p $HOME/.vim/colors/
    ln -frs .vim/colors/nixpulvis.vim $HOME/.vim/colors/
}

install_ssh() {
    mkdir -p $HOME/.ssh
    cp -f .ssh/id_rsa.pub $HOME/.ssh/
    chmod 700 $HOME/.ssh
    chmod 644 $HOME/.ssh/id_rsa.pub

    # TODO: install private key, and set it to 600.
}

install_git() {
    ln -frs .gitconfig $HOME/.gitconfig
    ln -frs .gitignore $HOME/.gitignore
}

install_ruby() {
    # Don't reinstall, this takes time.
    if [ ! -x "$(command -v ruby)" ]; then
        # Install Ruby, and our ruby environment.
        if [[ ! -d $HOME/.rbenv ]]; then
            git clone https://github.com/rbenv/rbenv.git $HOME/.rbenv
            mkdir $HOME/.rbenv/plugins
            git clone https://github.com/rbenv/ruby-build.git $HOME/.rbenv/plugins/ruby-build
        fi
    fi

    $HOME/.rbenv/bin/rbenv install --skip-existing 2.5.0
    $HOME/.rbenv/bin/rbenv rehash
}

install_rust() {
    # Don't reinstall.
    if [ ! -x "$(command -v rustc)" ]; then
        # Install rustup and stable rust.
        sudo pacman -S --noconfirm rustup
        rustup toolchain install stable
        rustup default stable

        # Allows running rust files as scripts.
        cargo install --force cargo-script
    fi
}

install_wm() {
    # Install the Xorg server.
    sudo pacman -S --needed --noconfirm xorg xorg-xinit

    # Pulseaudio et. all
    sudo pacman -S --needed --noconfirm pulseaudio pulseaudio-alsa alsa-utils

    # Install sway/i3 WM, and supporting tools.
    sudo pacman -S --needed --noconfirm sway i3-wm i3blocks dmenu rofi feh \
        sysstat acpi xautolock deepin-screenshot swayidle swaybg htop
    yaourt -S --needed --noconfirm swaylock-effects-git
    yaourt -S --needed --noconfirm i3lock-color
    yaourt -S --needed --noconfirm brightnessctl
    yaourt -S --needed --noconfirm rofimoji

    # Install font-awesome for icons.
    yaourt -S --noconfirm ttf-font-awesome

    ln -frs .xinitrc $HOME/.xinitrc
    mkdir -p $HOME/.X
    ln -frs .X/backdrop* $HOME/.X
    mkdir -p $HOME/.config/sway
    ln -frs .config/sway/{config,lock,screenshot} $HOME/.config/sway/
    mkdir -p $HOME/.config/i3
    ln -frs .config/i3/{config,launch,open,rofimoji,terminal,exit,mute,lock} $HOME/.config/i3/
    mkdir -p $HOME/.config/i3blocks
    ln -frs .config/i3blocks/{config,iface,bandwidth,battery,brightness,cpu_usage,disk,load_average,memory,mic,temperature,volume,wifi,_date,time} $HOME/.config/i3blocks/

    mkdir -p $HOME/.config/rofi
    ln -frs .config/rofi/nixpulvis.rasi $HOME/.config/rofi/

    # Setup default home directories.
    ln -frs .config/user-dirs.dirs $HOME/.config/user-dirs.dirs

    # Set default desktop wallpaper randomly.
    choice=`shuf -i 1-4 -n 1`
    ln -frs $HOME/.X/backdrop${choice}.png $HOME/.X/backdrop.png

    # Add a `~/Desktop` directory, this is the default location for
    # screenshots.
    mkdir -p $HOME/Desktop

    yaourt -S --noconfirm grim slurp
}

install_browser() {
    # TODO: Configure a custom firefox theme.
    sudo pacman -S --needed --noconfirm firefox
}

install_pdf() {
    sudo pacman -S --needed --noconfirm zathura zathura-pdf-poppler
    mkdir -p $HOME/.config/zathura
    ln -frs .config/zathura/zathurarc $HOME/.config/zathura/

    # TODO: LaTeX
}

install_media() {
    sudo pacman -S --needed --noconfirm vlc
}

install_torrent() {
    # Install Transmission a P2P file transfer software.
    sudo pacman -S --needed --noconfirm transmission-cli
}


# Here be the magic, in order.

# Better package management.
install_yaourt

# Basic System
install_fonts
install_terminal
install_shell

# Tools
install_bin
install_editor
install_ssh
install_git
install_ruby
install_rust
install_wm
install_browser
install_pdf
install_torrent
