#!/bin/bash
set -e

# Install our terminal emulator.
yaourt -S --needed --noconfirm alacritty-scrollback-git

# Install needed tool for `spawn-alacritty-cwd`.
sudo pacman -S --needed --noconfirm xdotool

mkdir -p $HOME/.config/alacritty
ln -frs alacritty.yml $HOME/.config/alacritty/alacritty.yml
ln -frs spawn-alacritty-cwd $HOME/.bin/spawn-alacritty-cwd

