#!/bin/bash

# Setup the systems locale configuration. This includes language, date, and
# time settings.

# Setup the locale.
sed -ie "s/#en_US\.UTF/en_US.UTF/" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

# Setup the timezone for correct local system time.
# TODO: Configurable, default to UTC.
timedatectl set-timezone America/Denver

# Set the system clock to use NTP.
timedatectl set-ntp true

# Set the hardware clock based on the system clock, however the HW clock
# will be set in UTC.
timedatectl set-local-rtc 0
hwclock --systohc

