#!/bin/bash

STEP=10
URGENT=20

case $BLOCK_BUTTON in
  1) brightnessctl -q s "80%" ;;
  3) brightnessctl -q s "20%" ;;
  4) brightnessctl -q s "+$STEP%" ;;
  5) brightnessctl -q s "$STEP%-" ;;
esac

max=$(brightnessctl max)
current=$(brightnessctl get)
percent=$(echo "scale=1; $current/$max * 100" | bc -l | sed 's/\.0$//')

if [[ "${percent}" == 0 ]]; then
  msg="-------------------------------------- "
  msg+="THE BRIGHTNESS IS OFF, CLICK HERE TO TURN BACK ON THE LIGHTS!"
  msg+=" --------------------------------------"
  echo $msg
  echo $msg
  echo "#CACACA"
  echo "#FE340A"
  exit 33
else
  echo "${percent}%"
  echo "${percent}%"
  [[ "${percent}" -le "${URGENT}" ]] && exit 33
  exit 0
fi
