#!/bin/sh

step=10
case $BLOCK_BUTTON in
  1) sudo light -S 80 ;;
  3) sudo light -S 20 ;;
  4) sudo light -A $step ;;
  5) sudo light -U $step ;;
esac

URGENT_VALUE=10

curBrightness=$(light)
if (( $(echo "${curBrightness} < 0.0" | bc -l) )); then
  exit
fi

percent=$(echo "scale=0;${curBrightness}" | bc -l)
percent=${percent%.*}

# TODO: Used to simply not print anything.
# if [[ "${percent}" -le 0 ]]; then
#   echo -n "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
#   echo -n "BRIGHTNESS OFF"
#   echo    "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
#   echo    "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
#   echo "#FE340A"
#   echo "#FE340A"
#   exit
# fi

echo "${percent}%"
echo "${percent}%"
# echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

