#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  light -A 10
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  light -U 10
fi

URGENT_VALUE=20

curBrightness=$(light)
if [[ "${curBrightness}" -le 0 ]]; then
  exit
fi

percent=$(echo "scale=0;${curBrightness}" | bc -l)
percent=${percent%.*}
if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "${percent}%"
echo "${percent}%"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

