#!/bin/bash
# Copyright (C) 2015 Martín Cigorraga <archlinux.us: msx>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DEFAULT_SOURCE=$(pactl info | grep "Default Source" | cut -d' ' -f3)

# Check mouse event
case $BLOCK_BUTTON in
    3)
    /usr/bin/pactl set-source-mute $DEFAULT_SOURCE toggle;  # PulseAudio
esac

# Determine mic's state
state=$(pactl get-source-mute $DEFAULT_SOURCE | cut -d' ' -f2)

# Toggle mic's state
case $state in
    yes)
    echo "  mute";
    exit 0;
    ;;
    no)
    echo "  open ";
    exit 33;
    ;;
    *)
    echo "no mic";
    exit 0;
    ;;
esac

exit 0;
